Repository 1-hummingbird/Back_Server_Side_App, pull requests merged in 2024-09, with the labels that each got.

#36 상품 필터링 쿼리 수정 및 배너 작업
  src/main/generated/com/hummingbird/kr/starbuckslike/banner/domain/QBanner.java
  src/main/generated/com/hummingbird/kr/starbuckslike/banner/dto/QBannerDto.java
  src/main/generated/com/hummingbird/kr/starbuckslike/category/dto/QCategoryListDto.java
  src/main/generated/com/hummingbird/kr/starbuckslike/product/dto/QProductListDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/banner/domain/Banner.java
  src/main/java/com/hummingbird/kr/starbuckslike/banner/dto/BannerDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/banner/infrastructure/BannerRepository.java
  src/main/java/com/hummingbird/kr/starbuckslike/banner/infrastructure/search/BannerSearch.java
  src/main/java/com/hummingbird/kr/starbuckslike/banner/infrastructure/search/BannerSearchImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/domain/Category.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/dto/CategoryListDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/infrastructure/search/CategorySearch.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/infrastructure/search/CategorySearchImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/config/LoadTestData.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/dto/ProductListDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/infrastructure/condition/ProductCondition.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/infrastructure/search/ProductSearchImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/presentation/ProductController.java
  src/test/java/com/hummingbird/kr/starbuckslike/banner/infrastructure/search/BannerSearchTest.java
  src/test/java/com/hummingbird/kr/starbuckslike/temp/repository/search/CategorySearchTest.java
Labels: contruction

#41 Feature/30
  src/main/java/com/hummingbird/kr/starbuckslike/category/domain/Category.java
  src/main/java/com/hummingbird/kr/starbuckslike/config/LoadTestData.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/domain/Member.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/domain/Product.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/infrastructure/search/ProductSearch.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/infrastructure/search/ProductSearchImpl.java
Labels: enhancement

#45 장바구니 컨트롤러 계층 외 작업, querydsl 설정
  src/main/generated/com/hummingbird/kr/starbuckslike/cart/domain/QCart.java
  src/main/generated/com/hummingbird/kr/starbuckslike/cart/dto/QResponseCartItemDto.java
  src/main/generated/com/hummingbird/kr/starbuckslike/cart/dto/QResponseCartItemImageDto.java
  src/main/generated/com/hummingbird/kr/starbuckslike/cart/dto/QResponseCartItemListDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/banner/domain/Banner.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/application/CartService.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/application/CartServiceImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/domain/Cart.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/domain/CartAdjustType.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/domain/CartStatus.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/dto/CartListDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/dto/RequestAddCartItemDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/dto/RequestAdjustCartItemDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/dto/RequestSelectCartItemDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/dto/ResponseCartItemDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/dto/ResponseCartItemImageDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/dto/ResponseCartItemListDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/infrastructure/CartRepository.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/infrastructure/custom/CustomCartRepository.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/infrastructure/custom/CustomCartRepositoryImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/infrastructure/search/CartSearch.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/infrastructure/search/CartSearchImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/presentation/CartController.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/domain/Category.java
  src/main/java/com/hummingbird/kr/starbuckslike/common/entity/CommonResponseEntity.java
  src/main/java/com/hummingbird/kr/starbuckslike/config/LoadTestData.java
  src/main/java/com/hummingbird/kr/starbuckslike/config/QueryDslConfig.java
  src/main/java/com/hummingbird/kr/starbuckslike/exhibition/domain/Exhibition.java
  src/main/java/com/hummingbird/kr/starbuckslike/exhibition/domain/ExhibitionProduct.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/domain/Product.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/domain/ProductImage.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/domain/ProductOption.java
  src/test/java/com/hummingbird/kr/starbuckslike/cart/infrastructure/search/CartSearchTest.java
Labels: contruction

#50 49 config for swagger api docs service
  .gitignore
  src/main/java/com/hummingbird/kr/starbuckslike/config/SwaggerConfig.java
Labels: documentation

#54 :fire: mainphone add
  src/main/generated/com/hummingbird/kr/starbuckslike/delivery/domain/QDelivery.java
  src/main/generated/com/hummingbird/kr/starbuckslike/member/domain/QMember.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/application/AuthService.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/application/AuthServiceImpl.Java
  src/main/java/com/hummingbird/kr/starbuckslike/delivery/domain/Delivery.java
  src/main/java/com/hummingbird/kr/starbuckslike/delivery/dto/DeliveryRequestDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/delivery/presentation/DeliveryController.java
  src/main/java/com/hummingbird/kr/starbuckslike/delivery/vo/DeliveryRequestVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/delivery/vo/DeliveryResponseVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/domain/Member.java
Labels: contruction

#55 :sparkles: make util class date-localdate converter
  src/main/java/com/hummingbird/kr/starbuckslike/common/utils/DateLocalDateConverter.java
Labels: contruction

#57 Feature/40 상품 컨트롤러 마무리
  .gitignore
  src/main/generated/com/hummingbird/kr/starbuckslike/cart/dto/out/QResponseCartItemDto.java
  src/main/generated/com/hummingbird/kr/starbuckslike/cart/dto/out/QResponseCartItemImageDto.java
  src/main/generated/com/hummingbird/kr/starbuckslike/category/dto/out/QChildCategoryResponseDto.java
  src/main/generated/com/hummingbird/kr/starbuckslike/category/dto/out/QMainCategoryResponseDto.java
  src/main/generated/com/hummingbird/kr/starbuckslike/exhibition/dto/out/QExhibitionDetailResponseDto.java
  src/main/generated/com/hummingbird/kr/starbuckslike/exhibition/dto/out/QExhibitionListResponseDto.java
  src/main/generated/com/hummingbird/kr/starbuckslike/product/dto/out/QProductDetailResponseDto.java
  src/main/generated/com/hummingbird/kr/starbuckslike/product/dto/out/QProductImageResponseDto.java
  src/main/generated/com/hummingbird/kr/starbuckslike/product/dto/out/QProductInfoResponseDto.java
  src/main/generated/com/hummingbird/kr/starbuckslike/product/dto/out/QProductListImageResponseDto.java
  src/main/generated/com/hummingbird/kr/starbuckslike/product/dto/out/QProductListInfoResponseDto.java
  src/main/generated/com/hummingbird/kr/starbuckslike/product/dto/out/QProductListResponseDto.java
  src/main/generated/com/hummingbird/kr/starbuckslike/product/dto/out/QProductOptionResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/dto/in/RequestAddCartItemDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/dto/out/ResponseCartItemDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/dto/out/ResponseCartItemImageDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/presentation/CartController.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/application/CategoryService.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/application/CategoryServiceImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/dto/out/BottomCategoryResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/dto/out/ChildCategoryResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/dto/out/MainCategoryResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/dto/out/MiddleCategoryResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/dto/out/Testdtodto.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/dto/out/TopCategoryResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/infrastructure/search/CategorySearch.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/infrastructure/search/CategorySearchImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/presentation/CategoryController.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/vo/ChildCategoryResponseVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/config/LoadTestData.java
  src/main/java/com/hummingbird/kr/starbuckslike/exhibition/dto/out/ExhibitionDetailResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/exhibition/dto/out/ExhibitionListResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/application/ProductService.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/application/ProductServiceImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/dto/out/ProductDetailResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/dto/out/ProductImageResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/dto/out/ProductInfoResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/dto/out/ProductListImageResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/dto/out/ProductListInfoResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/dto/out/ProductListResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/dto/out/ProductOptionResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/infrastructure/condition/ProductCondition.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/infrastructure/search/ProductSearch.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/infrastructure/search/ProductSearchImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/presentation/ProductController.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/vo/ProductListImageResponseVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/vo/ProductListInfoResponseVo.java
Labels: contruction

#63 :construction_worker: Add dockerfile
  Dockerfile
Labels: contruction

#68 :rotating_light: Update build.gradle
  build.gradle
Labels: bug

#69 👷 Update deploy-dev.yml
  .github/workflows/deploy-dev.yml
Labels: bug

#70 Song
  src/main/java/com/hummingbird/kr/starbuckslike/cart/infrastructure/search/CartSearchImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/delivery/application/DeliveryService.java
  src/main/java/com/hummingbird/kr/starbuckslike/delivery/application/DeliveryServiceImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/delivery/domain/Delivery.java
  src/main/java/com/hummingbird/kr/starbuckslike/delivery/dto/DeliveryRequestDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/delivery/infrastructure/DeliveryRepository.java
  src/main/java/com/hummingbird/kr/starbuckslike/delivery/presentation/DeliveryController.java
  src/main/java/com/hummingbird/kr/starbuckslike/delivery/vo/DeliveryRequestVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/delivery/vo/DeliveryResponseVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/application/ShippingAddressService.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/application/ShippingAddressServiceImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/domain/ShippingAddress.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/dto/in/ShippingAddressDefaultChangeDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/dto/in/ShippingAddressRequestDTo.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/dto/in/ShippingAddressUpdateDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/infrastructure/ShippingAddressRepository.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/presentation/ShippingAddressController.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/vo/in/ShippingAddressRequestVo.java
  src/test/java/com/hummingbird/kr/starbuckslike/temp/repository/ProductRepositoryTest.java
Labels: contruction

#75 :construction_worker: Update deploy-dev.yml
  .github/workflows/deploy-dev.yml
Labels: bug

#81 🛂 for Preventing Dupulicate Register, check Phone, Email, LoginID API added
  src/main/java/com/hummingbird/kr/starbuckslike/auth/application/AuthService.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/application/AuthServiceImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/domain/OauthInfo.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/dto/in/CheckEmailRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/dto/in/CheckLoginIDRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/dto/in/CheckPhoneRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/dto/in/EmailVerificationCheckRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/dto/in/EmailVerificationRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/dto/in/OauthLoginRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/dto/in/OauthRegisterRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/dto/in/PhoneVerificationCheckRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/dto/in/PhoneVerificationRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/dto/in/WithdrawRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/dto/out/CheckEmailResponseDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/dto/out/CheckLoginIDResponseDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/dto/out/CheckPhoneResponseDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/infrastructure/AuthRepository.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/infrastructure/OauthInfoRepository.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/presentation/AuthController.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/vo/in/CheckEmailRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/vo/in/CheckLoginIDRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/vo/in/CheckPhoneRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/vo/in/EmailVerificationCheckRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/vo/in/EmailVerificationRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/vo/in/OauthLoginRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/vo/in/OauthRegisterRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/vo/in/PhoneVerificationCheckRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/vo/in/PhoneVerificationRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/vo/in/WithdrawRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/vo/out/CheckEmailResponseVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/vo/out/CheckLoginIDResponseVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/vo/out/CheckPhoneResponseVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/config/RedisConfig.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/application/MemberService.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/application/MemberServiceImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/domain/Member.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/in/CanReviewRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/in/MemberInfoRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/in/MemberUpdateRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/in/PurchaseRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/in/RefundRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/out/CanReviewResponseDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/out/MemberInfoResponseDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/out/PurchaseResponseDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/infrastructrue/MemberRepository.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/presentation/MemberController.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/in/CanReviewRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/in/MemberInfoRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/in/MemberUpdateRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/in/PurchaseRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/in/RefundRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/out/CanReviewResponseVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/out/MemberInfoResponseVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/out/PurchaseResponseVO.java
Labels: enhancement, contruction

#83 Feature/82 리뷰 도메인 70% 작업
  src/main/java/com/hummingbird/kr/starbuckslike/cart/application/CartService.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/application/CartServiceImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/domain/Cart.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/dto/in/RequestAddCartItemDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/dto/out/ResponseCartItemDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/infrastructure/custom/CustomCartRepositoryImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/infrastructure/search/CartSearch.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/infrastructure/search/CartSearchImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/presentation/CartController.java
  src/main/java/com/hummingbird/kr/starbuckslike/cart/vo/ResponseCartItemVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/domain/BottomCategory.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/domain/MiddleCategory.java
  src/main/java/com/hummingbird/kr/starbuckslike/category/domain/TopCategory.java
  src/main/java/com/hummingbird/kr/starbuckslike/common/utils/PurchaseCodeGenerator.java
  src/main/java/com/hummingbird/kr/starbuckslike/config/LoadTestData.java
  src/main/java/com/hummingbird/kr/starbuckslike/exhibition/infrastructure/search/ExhibitionSearchImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/purchase/application/PurchaseService.java
  src/main/java/com/hummingbird/kr/starbuckslike/purchase/application/PurchaseServiceImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/purchase/domain/Purchase.java
  src/main/java/com/hummingbird/kr/starbuckslike/purchase/dto/in/AddPurchaseItemRequestDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/purchase/dto/in/AddPurchaseRequestDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/purchase/dto/out/PurchaseDetailResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/purchase/dto/out/PurchaseItemResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/purchase/dto/out/PurchaseListResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/purchase/infrastructure/PurchaseRepository.java
  src/main/java/com/hummingbird/kr/starbuckslike/purchase/infrastructure/search/PurchaseSearch.java
  src/main/java/com/hummingbird/kr/starbuckslike/purchase/infrastructure/search/PurchaseSearchImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/purchase/presentation/PurchaseController.java
  src/main/java/com/hummingbird/kr/starbuckslike/purchase/vo/in/AddPurchaseItemRequestVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/purchase/vo/in/AddPurchaseRequestVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/purchase/vo/out/PurchaseDetailResponseVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/purchase/vo/out/PurchaseItemResponseVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/purchase/vo/out/PurchaseListResponseVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/application/ReviewService.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/application/ReviewServiceImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/domain/Review.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/domain/ReviewComment.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/domain/ReviewImage.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/dto/in/AddReviewCommentRequestDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/dto/in/AddReviewImageRequestDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/dto/in/AddReviewRequestDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/dto/in/DeleteReviewCommentRequestDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/dto/out/ReviewCommentResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/dto/out/ReviewListImageResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/dto/out/ReviewListInfoResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/infrastructure/ReviewCommentRepository.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/infrastructure/ReviewImageRepository.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/infrastructure/ReviewRepository.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/infrastructure/search/ReviewSearch.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/infrastructure/search/ReviewSearchImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/presentation/ReviewController.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/vo/in/AddReviewCommentRequestVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/vo/in/AddReviewImageRequestVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/vo/in/AddReviewRequestVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/vo/in/DeleteReviewCommentRequestVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/vo/out/ReviewCommentResponseVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/vo/out/ReviewListImageResponseVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/vo/out/ReviewListInfoResponseVo.java
Labels: contruction

#86 ✨ 🚑 [Emergency] Can't login from front #85 / [Feature] member Info get(use post method relate to Privacy Security Issue)
  src/main/java/com/hummingbird/kr/starbuckslike/auth/application/AuthServiceImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/domain/AuthUserDetail.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/dto/in/RegisterRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/presentation/AuthController.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/vo/in/RegisterRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/config/LoadTestData.java
  src/main/java/com/hummingbird/kr/starbuckslike/config/RedisConfig.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/application/MemberService.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/application/MemberServiceImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/domain/Member.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/domain/MemberInfo.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/in/CanReviewRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/in/FindMemberRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/in/MemberInfoRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/in/PassageRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/in/PurchaseRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/in/RefundRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/out/CanReviewResponseDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/out/FindMemberResponseDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/out/MemberInfoResponseDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/out/PurchaseResponseDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/presentation/MemberController.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/in/CanReviewRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/in/FindMemberRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/in/MemberInfoRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/in/PassageRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/in/PurchaseRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/in/RefundRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/out/CanReviewResponseVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/out/FindMemberResponseVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/out/MemberInfoResponseVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/out/PurchaseResponseVO.java
Labels: bug, contruction

#87 🚑 try about issue #85
  src/main/java/com/hummingbird/kr/starbuckslike/config/SecurityConfig.java
Labels: bug

#89 Basic Spring Security Applying Complet
  src/main/java/com/hummingbird/kr/starbuckslike/auth/application/AuthService.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/application/AuthServiceImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/dto/in/UpdatePWRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/presentation/AuthController.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/vo/in/UpdatePWRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/config/SecurityConfig.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/application/MemberServiceImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/domain/Member.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/in/FindMemberRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/dto/in/MemberUpdateRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/presentation/MemberController.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/in/FindMemberRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/vo/in/MemberUpdateRequestVO.java
Labels: contruction

#95 ✨ Shipping Address Service Complete
  src/main/java/com/hummingbird/kr/starbuckslike/auth/vo/in/OauthLoginRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/vo/in/OauthRegisterRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/vo/in/PhoneVerificationCheckRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/common/entity/BaseResponseStatus.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/domain/Member.java
  src/main/java/com/hummingbird/kr/starbuckslike/member/presentation/MemberController.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/application/ShippingAddressService.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/application/ShippingAddressServiceImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/application/ShippingService.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/application/ShippingServiceImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/domain/ShippingAddress.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/domain/ShippingSetting.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/dto/in/ShippingAddressAddRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/dto/in/ShippingAddressDefaultChangeDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/dto/in/ShippingAddressDeleteRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/dto/in/ShippingAddressRequestDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/dto/in/ShippingAddressSetDefaultRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/dto/in/ShippingAddressUpdateDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/dto/in/ShippingAddressUpdateRequestDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/dto/out/ShippingAddressGetDefaultResponseDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/dto/out/ShippingAddressListResponseDTO.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/infrastructure/ShippingAddressRepository.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/infrastructure/ShippingSettingRepository.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/presentation/ShippingAddressController.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/vo/in/ShippingAddressAddRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/vo/in/ShippingAddressDeleteRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/vo/in/ShippingAddressRequestVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/vo/in/ShippingAddressSetDefaultRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/vo/in/ShippingAddressUpdateRequestVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/vo/out/ShippingAddressGetDefaultResponseVO.java
  src/main/java/com/hummingbird/kr/starbuckslike/shipping/vo/out/ShippingAddressListResponseVO.java
Labels: contruction

#96 Feature/94 #94 포토리뷰 검색조건 , 상품명 검색조건 적용
  src/main/java/com/hummingbird/kr/starbuckslike/config/LoadTestData.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/infrastructure/condition/ProductCondition.java
  src/main/java/com/hummingbird/kr/starbuckslike/product/infrastructure/search/ProductSearchImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/redis/facade/ReviewLockFacade.java
  src/main/java/com/hummingbird/kr/starbuckslike/redis/infrastructure/RedisLockRepository.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/application/ReviewService.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/application/ReviewServiceImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/domain/Review.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/dto/in/AddReviewRequestDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/dto/out/ReviewListInfoResponseDto.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/infrastructure/ReviewRepository.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/infrastructure/condition/ReviewCondition.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/infrastructure/search/ReviewSearch.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/infrastructure/search/ReviewSearchImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/presentation/ReviewController.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/vo/in/AddReviewImageRequestVo.java
  src/main/java/com/hummingbird/kr/starbuckslike/review/vo/in/AddReviewRequestVo.java
  src/test/java/com/hummingbird/kr/starbuckslike/redis/service/RedisServiceTest.java
Labels: enhancement

#97 ✨ Logout API complete
  src/main/java/com/hummingbird/kr/starbuckslike/auth/application/AuthServiceImpl.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/presentation/AuthController.java
  src/main/java/com/hummingbird/kr/starbuckslike/auth/util/JwtAuthenticationFilter.java
  src/main/java/com/hummingbird/kr/starbuckslike/redis/service/RedisService.java
  src/main/java/com/hummingbird/kr/starbuckslike/redis/service/RedisServiceImpl.java
Labels: enhancement

#122 :bug: :technologist: fix bug if duplicated loginID or phone or email
  src/main/java/com/hummingbird/kr/starbuckslike/auth/application/AuthServiceImpl.java
Labels: enhancement
